### ISSUE TITLE
How to connect.

### ISSUE THREAD

**Issue by mike-0346** [JurajNyiri/HomeAssistant-Lights-App#2]
Hello i have the integration via HACS but no devices show up. How can i merge the devices in the app to the Integration?
![Screenshot_2024-11-27-19-16-56-80_0a6d1184a1e3bfe9e82a818d5d438d8f](https://github.com/user-attachments/assets/89be4c14-f89c-4fb3-bd39-b7b3433a4a3c)
![Screenshot_2024-11-27-19-17-00-81_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/f2358a6e-0df6-4ee2-81df-7b850f4aeedb)

**Comment by flobbe** [comment]
Make sure that your Home Assistant server has a Bluetooth adapter and can see the fairy lights.
I also initially thought that I could control it with my phone, but it only ever shows me “no_devices_found”.
As my server is not near my fairy lights, I now use an ESP32 device as a BT proxy: https://esphome.io/projects/?type=bluetooth
You can also connect a BT dongle directly to the server.

**Comment by mike-0346** [comment]
Oke thanks! i will try to set up a bluetooth proxy
