### ISSUE TITLE
Initializing

### ISSUE THREAD

**Issue by Chewb4cc4** [JurajNyiri/HomeAssistant-Lights-App#5]
Unfortunately, the integration gets stuck during initialization for me.

![image](https://github.com/user-attachments/assets/a84ae836-1990-492b-9862-95a8289536c5)

![image](https://github.com/user-attachments/assets/1d776044-e688-4930-ae10-5d5e47a6b3e1)

**Comment by Cubixzno1** [comment]
Mine does it all the time. Works for 10 hours and then just dies.. 

@Chewb4cc4 have yours been working since?
