### ISSUE TITLE
No device found after HACS installation LED-4-01-00000000 AX8-718902

### ISSUE THREAD

**Issue by barthel-eu** [JurajNyiri/HomeAssistant-Lights-App#7]
Upon installing from the repository added to HACS, I can see the Lights App in the devices, but trying to add the integration I get
```
Lights App
no_devices_found
```
So the integration fails. The device name LED-4-01-00000000 (5.5m variant) is in the supported SUPPORTED_BLUETOOTH_NAMES in the CONST.PY (checked).

Any beginners error (PEBKAS) on my side?

And yes, I restarted Home Assistant after integration (twice).

![tmp1](https://github.com/user-attachments/assets/dcef27fe-251c-4902-9146-d9933bfd8635)
![tmp2](https://github.com/user-attachments/assets/da7b2c45-88d6-4042-a819-9688450961a8)
![tmp3](https://github.com/user-attachments/assets/020a8255-1813-4f3a-9a34-19a37a892e34)

**Comment by JurajNyiri** [comment]
Does your HA instance contain a bluetooth device that can reach and has a capacity to reach the light chain?

**Comment by barthel-eu** [comment]
Okay to close. After about three hours (we were out), the Lights App suddenly showed up in HA as a new device. It allows switch-on/off, all other settings show unavailable (as others reported already).
