### ISSUE TITLE
LED-4-02-00000000 integration issues

### ISSUE THREAD

**Issue by MiroG225** [JurajNyiri/HomeAssistant-Lights-App#8]
I bought the LED-4-02-00000000, and here is my experience.
I checked in the supermarket to confirm that the integration exists. Unfortunately, I didn’t read the reported issues beforehand.

The first time, I installed the integration by copying the custom_components folder. I was able to find the device and integrate it into Home Assistant (HA) with all controls available.
However, the connection was very unstable:

![image](https://github.com/user-attachments/assets/8774d68a-9998-49ca-b85c-0bcb73c43905)

Then I tried to completely remove the integration and installed it via HACS.
This time, the integration could detect the device but failed to integrate it, showing the following note:

![image](https://github.com/user-attachments/assets/6d8e8c3f-13ed-4ee1-8788-af55ae27554f)

The device's Bluetooth is visible on my mobile, and I can pair it using the Lights App application. The LED-4-02-00000000 is defined in the const.py file.

This is where I am at the moment.
Do you have any suggestions?

Is there a way to reboot the device? I couldn't find this information in the user guide.

By the way, is it true that anyone near the device can control it? For example, could my neighbor access it? There doesn’t seem to be any device lock, pairing code, or similar security feature.

**Comment by JurajNyiri** [comment]
Yes anyone can control it.
HA instance needs better bluetooth, then connection would be more stable.

**Comment by MiroG225** [comment]
Thanks for pointing me in the right direction. I have an internal Bluetooth module in my RPI4. I disabled it and used a Realtek USB Bluetooth dongle instead. Suddenly, the device connected successfully.

I’ll update here regarding the stability of the connection.
In case of instability I'll try to use USB extension cable (as I use for Zigbee dongle)

Many thanks
